#!/usr/bin/env python3
"""
IEC 62443-3-3 Dataset Audit
===========================

Audits the outputs generated by the LLM-assisted IEC extraction pipeline.

Inputs:
    data/output/datasets/iec62443_clean.json
    data/output/datasets/iec62443_debug.json

Outputs:
    data/output/datasets/iec62443_audit.json
    data/output/datasets/iec62443_audit_report.txt

The script DOES NOT modify the clean dataset.

Audit layers:
    1. Dataset structure
    2. Requirement ID validation
    3. Expected IEC SR coverage
    4. SR/RE hierarchy validation
    5. Foundational Requirement consistency
    6. Text quality and possible contamination
    7. Candidate consistency across debug blocks
    8. Clean dataset consistency with debug consolidation
    9. Duplicate detection
    10. Per-entry quality score

"""

import json
import re
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from difflib import SequenceMatcher
from pathlib import Path
from typing import Any


# =============================================================================
# CONFIGURATION
# =============================================================================

BASE_DIR = Path("data/output/datasets")

CLEAN_JSON_PATH = BASE_DIR / "iec62443_clean.json"
DEBUG_JSON_PATH = BASE_DIR / "iec62443_debug.json"

AUDIT_JSON_PATH = BASE_DIR / "iec62443_audit.json"
AUDIT_REPORT_PATH = BASE_DIR / "iec62443_audit_report.txt"


EXPECTED_SRS = {
    1: 13,
    2: 12,
    3: 9,
    4: 3,
    5: 4,
    6: 2,
    7: 8,
}

EXPECTED_TOTAL_SRS = sum(EXPECTED_SRS.values())
EXPECTED_TOTAL_RES = 49
EXPECTED_TOTAL_ENTRIES = EXPECTED_TOTAL_SRS + EXPECTED_TOTAL_RES


# =============================================================================
# REGULAR EXPRESSIONS
# =============================================================================

SR_ID_PATTERN = re.compile(
    r"^SR\s+([1-7])\.(\d+)$",
    re.IGNORECASE,
)

RE_ID_PATTERN = re.compile(
    r"^SR\s+([1-7])\.(\d+)\s+RE\s+(\d+)$",
    re.IGNORECASE,
)

ANY_ID_PATTERN = re.compile(
    r"^SR\s+[1-7]\.\d+(?:\s+RE\s+\d+)?$",
    re.IGNORECASE,
)


# =============================================================================
# TEXT CONTAMINATION MARKERS
# =============================================================================

# These markers indicate that explanatory or structural PDF content may have
# leaked into the normative requirement text.
CONTAMINATION_PATTERNS = {
    "rationale_and_guidance": re.compile(
        r"\bRationale\s+and\s+supplemental\s+guidance\b",
        re.IGNORECASE,
    ),

    "requirement_enhancements": re.compile(
        r"\bRequirement\s+enhancements?\b",
        re.IGNORECASE,
    ),

    "security_levels": re.compile(
        r"\bSecurity\s+levels?\b",
        re.IGNORECASE,
    ),

    "copyright_notice": re.compile(
        r"\bCopyright\b",
        re.IGNORECASE,
    ),

    "not_for_resale": re.compile(
        r"\bNot\s+for\s+Resale\b",
        re.IGNORECASE,
    ),

    "provided_by": re.compile(
        r"\bProvided\s+by\b",
        re.IGNORECASE,
    ),

    "licensee": re.compile(
        r"\bLicensee\s*=",
        re.IGNORECASE,
    ),

    "void_artifact": re.compile(
        r"\bVoid\b",
        re.IGNORECASE,
    ),

    "pdf_artifact": re.compile(
        r"--[`',\s\-]{5,}",
        re.IGNORECASE,
    ),
}


# =============================================================================
# NORMALIZATION
# =============================================================================

def normalize_whitespace(text: str) -> str:
    """
    Normalizes whitespace without changing semantic content.
    """
    if not isinstance(text, str):
        return ""

    return re.sub(r"\s+", " ", text).strip()


def normalize_for_comparison(text: str) -> str:
    """
    Produces a conservative normalized representation for comparisons.

    We intentionally do not perform aggressive linguistic normalization,
    stemming, or semantic rewriting because the audit must remain
    deterministic and reproducible.
    """
    text = normalize_whitespace(text).lower()

    # Normalize typographic apostrophes/quotes.
    text = (
        text.replace("’", "'")
        .replace("‘", "'")
        .replace("“", '"')
        .replace("”", '"')
    )

    return text


def text_similarity(a: str, b: str) -> float:
    """
    Sequence similarity in [0, 1].
    """
    a_norm = normalize_for_comparison(a)
    b_norm = normalize_for_comparison(b)

    if not a_norm and not b_norm:
        return 1.0

    if not a_norm or not b_norm:
        return 0.0

    return SequenceMatcher(
        None,
        a_norm,
        b_norm,
    ).ratio()


def is_prefix_variant(a: str, b: str) -> bool:
    """
    Returns True if one normalized string is a prefix of the other.

    This is useful for identifying block-boundary variants where one
    extraction captured a complete requirement and another captured a
    shorter version of the same text.
    """
    a_norm = normalize_for_comparison(a)
    b_norm = normalize_for_comparison(b)

    return (
        a_norm.startswith(b_norm)
        or b_norm.startswith(a_norm)
    )


# =============================================================================
# JSON LOADING
# =============================================================================

def load_json(path: Path) -> Any:
    """
    Loads JSON with explicit error messages.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"Required file not found:\n   {path}"
        )

    try:
        with path.open("r", encoding="utf-8") as file:
            return json.load(file)

    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Invalid JSON in:\n   {path}\n\n"
            f"JSON error:\n   {exc}"
        ) from exc


# =============================================================================
# IEC ID HELPERS
# =============================================================================

def parse_requirement_id(requirement_id: str) -> dict[str, Any]:
    """
    Parses an IEC requirement ID.

    Examples:
        SR 1.1
        SR 1.1 RE 2
    """

    result = {
        "valid": False,
        "type": None,
        "fr": None,
        "sr_number": None,
        "re_number": None,
        "parent_sr": None,
    }

    if not isinstance(requirement_id, str):
        return result

    requirement_id = normalize_whitespace(requirement_id)

    sr_match = SR_ID_PATTERN.fullmatch(requirement_id)

    if sr_match:
        fr = int(sr_match.group(1))
        sr_number = int(sr_match.group(2))

        result.update(
            {
                "valid": True,
                "type": "SR",
                "fr": fr,
                "sr_number": sr_number,
                "parent_sr": f"SR {fr}.{sr_number}",
            }
        )

        return result

    re_match = RE_ID_PATTERN.fullmatch(requirement_id)

    if re_match:
        fr = int(re_match.group(1))
        sr_number = int(re_match.group(2))
        re_number = int(re_match.group(3))

        result.update(
            {
                "valid": True,
                "type": "RE",
                "fr": fr,
                "sr_number": sr_number,
                "re_number": re_number,
                "parent_sr": f"SR {fr}.{sr_number}",
            }
        )

        return result

    return result


# =============================================================================
# EXPECTED SR IDs
# =============================================================================

def build_expected_sr_ids() -> set[str]:
    """
    Builds the expected set of 51 SR IDs.
    """

    expected = set()

    for fr, count in EXPECTED_SRS.items():
        for sr_number in range(1, count + 1):
            expected.add(f"SR {fr}.{sr_number}")

    return expected


EXPECTED_SR_IDS = build_expected_sr_ids()


# =============================================================================
# CLEAN DATASET INDEXING
# =============================================================================

def index_clean_requirements(
    requirements: list[dict[str, Any]]
) -> tuple[
    dict[str, dict[str, Any]],
    Counter,
]:
    """
    Builds an ID -> requirement index and counts duplicate IDs.
    """

    indexed = {}
    id_counts = Counter()

    for requirement in requirements:
        requirement_id = requirement.get("id")

        if not isinstance(requirement_id, str):
            continue

        requirement_id = normalize_whitespace(requirement_id)

        id_counts[requirement_id] += 1

        # Preserve the first occurrence for auditing.
        if requirement_id not in indexed:
            indexed[requirement_id] = requirement

    return indexed, id_counts


# =============================================================================
# DEBUG CANDIDATE INDEXING
# =============================================================================

def collect_debug_candidates(
    debug_data: dict[str, Any]
) -> dict[str, list[dict[str, Any]]]:
    """
    Collects every candidate occurrence of each requirement ID across blocks.

    Each occurrence preserves:
        - block_id
        - central_pages
        - context_pages
        - candidate fields
    """

    candidates_by_id = defaultdict(list)

    blocks = debug_data.get("blocks", [])

    if not isinstance(blocks, list):
        return candidates_by_id

    for block in blocks:
        if not isinstance(block, dict):
            continue

        block_id = block.get("block_id")
        central_pages = block.get("central_pages", [])
        context_pages = block.get("context_pages", [])

        requirements = block.get("requirements", [])

        if not isinstance(requirements, list):
            continue

        for requirement in requirements:
            if not isinstance(requirement, dict):
                continue

            requirement_id = requirement.get("id")

            if not isinstance(requirement_id, str):
                continue

            requirement_id = normalize_whitespace(requirement_id)

            occurrence = {
                "block_id": block_id,
                "central_pages": central_pages,
                "context_pages": context_pages,
                "id": requirement_id,
                "type": requirement.get("type"),
                "title": requirement.get("title"),
                "text": requirement.get("text"),
            }

            candidates_by_id[requirement_id].append(occurrence)

    return candidates_by_id


# =============================================================================
# CONTAMINATION AUDIT
# =============================================================================

def find_contamination(text: str) -> list[str]:
    """
    Returns all contamination categories detected in the text.
    """

    findings = []

    if not isinstance(text, str):
        return findings

    for name, pattern in CONTAMINATION_PATTERNS.items():
        if pattern.search(text):
            findings.append(name)

    return findings


# =============================================================================
# NORMATIVE TEXT HEURISTICS
# =============================================================================

def assess_normative_start(text: str) -> dict[str, Any]:
    """
    Performs a conservative heuristic check.

    IEC normative requirements generally contain 'shall'. We do not require
    that the text literally starts with 'The control system shall', because
    valid requirements may begin with conditional or contextual clauses.

    Examples:
        "If cryptography is required, the control system shall ..."
        "For software process and device users, ..."
        "On all interfaces, the control system shall ..."
    """

    normalized = normalize_whitespace(text)

    if not normalized:
        return {
            "status": "fail",
            "reason": "empty_text",
        }

    if " shall " in f" {normalized.lower()} ":
        return {
            "status": "pass",
            "reason": "contains_shall",
        }

    return {
        "status": "warning",
        "reason": "no_shall_detected",
    }


# =============================================================================
# DEBUG CONSISTENCY
# =============================================================================

def audit_debug_candidates(
    requirement_id: str,
    final_requirement: dict[str, Any],
    occurrences: list[dict[str, Any]],
) -> dict[str, Any]:
    """
    Audits consistency between:
        - all block-level candidates
        - final consolidated requirement
    """

    final_title = final_requirement.get("title", "")
    final_text = final_requirement.get("text", "")

    result = {
        "candidate_occurrences": len(occurrences),
        "unique_text_variants": 0,
        "unique_title_variants": 0,
        "min_text_similarity_to_final": None,
        "max_text_similarity_to_final": None,
        "average_text_similarity_to_final": None,
        "prefix_variants_detected": False,
        "exact_final_match_found": False,
        "title_variants": [],
        "text_variants": [],
        "issues": [],
    }

    if not occurrences:
        result["issues"].append("not_found_in_debug_blocks")
        return result

    normalized_texts = defaultdict(list)
    normalized_titles = defaultdict(list)

    similarities = []
    prefix_detected = False
    exact_match = False

    for occurrence in occurrences:

        title = occurrence.get("title", "")
        text = occurrence.get("text", "")

        title_key = normalize_for_comparison(title)
        text_key = normalize_for_comparison(text)

        normalized_titles[title_key].append(occurrence)
        normalized_texts[text_key].append(occurrence)

        similarity = text_similarity(final_text, text)
        similarities.append(similarity)

        if similarity >= 0.999:
            exact_match = True

        if is_prefix_variant(final_text, text) and similarity < 0.999:
            prefix_detected = True

    result["unique_text_variants"] = len(normalized_texts)
    result["unique_title_variants"] = len(normalized_titles)

    result["exact_final_match_found"] = exact_match
    result["prefix_variants_detected"] = prefix_detected

    if similarities:
        result["min_text_similarity_to_final"] = round(min(similarities), 4)
        result["max_text_similarity_to_final"] = round(max(similarities), 4)
        result["average_text_similarity_to_final"] = round(
            sum(similarities) / len(similarities),
            4,
        )

    # Record variants only when there is more than one distinct version.
    if len(normalized_titles) > 1:
        result["title_variants"] = [
            {
                "title": occurrences_for_variant[0].get("title"),
                "blocks": [
                    occurrence.get("block_id")
                    for occurrence in occurrences_for_variant
                ],
            }
            for occurrences_for_variant in normalized_titles.values()
        ]

        result["issues"].append("multiple_title_variants")

    if len(normalized_texts) > 1:
        result["text_variants"] = [
            {
                "text": occurrences_for_variant[0].get("text"),
                "blocks": [
                    occurrence.get("block_id")
                    for occurrence in occurrences_for_variant
                ],
            }
            for occurrences_for_variant in normalized_texts.values()
        ]

        result["issues"].append("multiple_text_variants")

    if not exact_match:
        result["issues"].append(
            "final_text_not_exactly_present_in_debug_candidates"
        )

    if prefix_detected:
        result["issues"].append("prefix_or_truncation_variant_detected")

    # Strong inconsistency:
    # the final text is substantially different from at least one candidate.
    if (
        result["min_text_similarity_to_final"] is not None
        and result["min_text_similarity_to_final"] < 0.70
    ):
        result["issues"].append("low_similarity_candidate_variant")

    return result


# =============================================================================
# DUPLICATE CONTENT DETECTION
# =============================================================================

def find_duplicate_content(
    requirements: list[dict[str, Any]]
) -> dict[str, list[str]]:
    """
    Detects exact normalized duplicate texts.

    Duplicate text is not automatically an error because some IEC requirements
    can legitimately have similar wording. Therefore this is reported as an
    observation rather than a structural failure.
    """

    by_text = defaultdict(list)

    for requirement in requirements:
        requirement_id = requirement.get("id")
        text = requirement.get("text", "")

        if not isinstance(requirement_id, str):
            continue

        normalized = normalize_for_comparison(text)

        if normalized:
            by_text[normalized].append(requirement_id)

    duplicates = {}

    for text, ids in by_text.items():
        if len(ids) > 1:
            duplicates[text] = ids

    return duplicates


# =============================================================================
# PER-ENTRY AUDIT
# =============================================================================

def audit_requirement(
    requirement: dict[str, Any],
    all_clean_ids: set[str],
    debug_candidates_by_id: dict[str, list[dict[str, Any]]],
    consolidated_debug: dict[str, Any],
) -> dict[str, Any]:
    """
    Performs the complete audit of one requirement.
    """

    requirement_id = normalize_whitespace(
        requirement.get("id", "")
    )

    requirement_type = requirement.get("type")
    title = requirement.get("title")
    text = requirement.get("text")
    parent_sr = requirement.get("parent_sr")
    foundational_requirement = requirement.get(
        "foundational_requirement"
    )

    issues = []
    warnings = []

    checks = {
        "valid_id": False,
        "valid_type": False,
        "title_present": False,
        "text_present": False,
        "parent_valid": False,
        "fr_consistent": False,
        "normative_text": False,
        "contamination_free": False,
        "debug_consistency": False,
    }

    # -------------------------------------------------------------------------
    # ID
    # -------------------------------------------------------------------------

    parsed = parse_requirement_id(requirement_id)

    if parsed["valid"]:
        checks["valid_id"] = True
    else:
        issues.append("invalid_requirement_id")

    # -------------------------------------------------------------------------
    # Type
    # -------------------------------------------------------------------------

    if requirement_type in {"SR", "RE"}:
        checks["valid_type"] = True
    else:
        issues.append("invalid_or_missing_type")

    # Ensure ID and declared type agree.
    if parsed["valid"] and requirement_type:
        if parsed["type"] != requirement_type:
            issues.append("id_type_mismatch")

    # -------------------------------------------------------------------------
    # Title
    # -------------------------------------------------------------------------

    if isinstance(title, str) and normalize_whitespace(title):
        checks["title_present"] = True
    else:
        issues.append("missing_title")

    # -------------------------------------------------------------------------
    # Text
    # -------------------------------------------------------------------------

    if isinstance(text, str) and normalize_whitespace(text):
        checks["text_present"] = True
    else:
        issues.append("missing_text")

    # -------------------------------------------------------------------------
    # Parent
    # -------------------------------------------------------------------------

    expected_parent = parsed["parent_sr"] if parsed["valid"] else None

    if (
        isinstance(parent_sr, str)
        and expected_parent
        and normalize_whitespace(parent_sr) == expected_parent
    ):

        if requirement_type == "SR":
            checks["parent_valid"] = True

        elif requirement_type == "RE":

            if expected_parent in all_clean_ids:
                checks["parent_valid"] = True
            else:
                issues.append("missing_parent_sr")

    else:
        issues.append("invalid_parent_sr")

    # -------------------------------------------------------------------------
    # Foundational Requirement
    # -------------------------------------------------------------------------

    if parsed["valid"]:

        if foundational_requirement == parsed["fr"]:
            checks["fr_consistent"] = True
        else:
            issues.append("foundational_requirement_mismatch")

    # -------------------------------------------------------------------------
    # Normative text
    # -------------------------------------------------------------------------

    normative = assess_normative_start(text)

    if normative["status"] == "pass":
        checks["normative_text"] = True
    else:
        warnings.append(normative["reason"])

    # -------------------------------------------------------------------------
    # Contamination
    # -------------------------------------------------------------------------

    contamination = find_contamination(text)

    if not contamination:
        checks["contamination_free"] = True
    else:
        for finding in contamination:
            issues.append(f"possible_text_contamination:{finding}")

    # -------------------------------------------------------------------------
    # Suspiciously short text
    # -------------------------------------------------------------------------

    word_count = len(normalize_whitespace(text).split())

    if word_count < 5:
        warnings.append("suspiciously_short_text")

    # -------------------------------------------------------------------------
    # Debug consistency
    # -------------------------------------------------------------------------

    occurrences = debug_candidates_by_id.get(
        requirement_id,
        [],
    )

    debug_audit = audit_debug_candidates(
        requirement_id,
        requirement,
        occurrences,
    )

    if not debug_audit["issues"]:
        checks["debug_consistency"] = True
    else:
        warnings.extend(debug_audit["issues"])

    # -------------------------------------------------------------------------
    # Consolidated debug comparison
    # -------------------------------------------------------------------------

    consolidated = consolidated_debug.get(requirement_id)

    consolidated_comparison = {
        "found": consolidated is not None,
        "id_match": None,
        "title_similarity": None,
        "text_similarity": None,
    }

    if isinstance(consolidated, dict):

        consolidated_comparison["id_match"] = (
            normalize_whitespace(
                consolidated.get("id", "")
            )
            == requirement_id
        )

        consolidated_comparison["title_similarity"] = round(
            text_similarity(
                title or "",
                consolidated.get("title", ""),
            ),
            4,
        )

        consolidated_comparison["text_similarity"] = round(
            text_similarity(
                text or "",
                consolidated.get("text", ""),
            ),
            4,
        )

        if (
            consolidated_comparison["text_similarity"]
            is not None
            and consolidated_comparison["text_similarity"] < 0.999
        ):
            warnings.append(
                "clean_text_differs_from_debug_consolidation"
            )

    else:
        warnings.append("missing_debug_consolidation_entry")

    # -------------------------------------------------------------------------
    # Score
    # -------------------------------------------------------------------------

    score = sum(
        1
        for value in checks.values()
        if value
    )

    max_score = len(checks)

    # -------------------------------------------------------------------------
    # Status
    # -------------------------------------------------------------------------

    critical_issues = {
        "invalid_requirement_id",
        "invalid_or_missing_type",
        "id_type_mismatch",
        "missing_title",
        "missing_text",
        "invalid_parent_sr",
        "missing_parent_sr",
        "foundational_requirement_mismatch",
    }

    has_critical = any(
        issue.split(":")[0] in critical_issues
        for issue in issues
    )

    has_contamination = any(
        issue.startswith("possible_text_contamination")
        for issue in issues
    )

    if has_critical:
        status = "fail"

    elif has_contamination:
        status = "review"

    elif score == max_score and not warnings:
        status = "approved"

    else:
        status = "warning"

    return {
        "id": requirement_id,
        "type": requirement_type,
        "title": title,
        "foundational_requirement": foundational_requirement,
        "parent_sr": parent_sr,

        "word_count": word_count,

        "score": score,
        "max_score": max_score,

        "status": status,

        "checks": checks,

        "issues": sorted(set(issues)),
        "warnings": sorted(set(warnings)),

        "contamination": contamination,

        "normative_text_assessment": normative,

        "debug_candidate_audit": debug_audit,

        "debug_consolidated_comparison": (
            consolidated_comparison
        ),
    }


# =============================================================================
# DATASET-LEVEL AUDIT
# =============================================================================

def audit_dataset(
    clean_data: dict[str, Any],
    debug_data: dict[str, Any],
) -> dict[str, Any]:
    """
    Runs all dataset-level and requirement-level audits.
    """

    requirements = clean_data.get("requirements", [])

    if not isinstance(requirements, list):
        raise RuntimeError(
            "The clean dataset does not contain a valid "
            "'requirements' list."
        )

    clean_index, id_counts = index_clean_requirements(
        requirements
    )

    all_clean_ids = set(clean_index.keys())

    duplicate_ids = {
        requirement_id: count
        for requirement_id, count in id_counts.items()
        if count > 1
    }

    debug_candidates_by_id = collect_debug_candidates(
        debug_data
    )

    consolidated_debug = debug_data.get(
        "consolidated_requirements",
        {},
    )

    if not isinstance(consolidated_debug, dict):
        consolidated_debug = {}

    # -------------------------------------------------------------------------
    # SR and RE counts
    # -------------------------------------------------------------------------

    sr_entries = [
        requirement
        for requirement in requirements
        if requirement.get("type") == "SR"
    ]

    re_entries = [
        requirement
        for requirement in requirements
        if requirement.get("type") == "RE"
    ]

    actual_sr_ids = {
        normalize_whitespace(
            requirement.get("id", "")
        )
        for requirement in sr_entries
        if isinstance(requirement.get("id"), str)
    }

    missing_srs = sorted(
        EXPECTED_SR_IDS - actual_sr_ids
    )

    unexpected_srs = sorted(
        actual_sr_ids - EXPECTED_SR_IDS
    )

    # -------------------------------------------------------------------------
    # FR distribution
    # -------------------------------------------------------------------------

    fr_distribution = {}

    for fr in range(1, 8):

        fr_srs = [
            requirement
            for requirement in sr_entries
            if requirement.get("foundational_requirement") == fr
        ]

        fr_res = [
            requirement
            for requirement in re_entries
            if requirement.get("foundational_requirement") == fr
        ]

        expected_sr_count = EXPECTED_SRS[fr]

        fr_distribution[str(fr)] = {
            "sr_count": len(fr_srs),
            "re_count": len(fr_res),
            "expected_sr_count": expected_sr_count,
            "sr_count_matches_expected": (
                len(fr_srs) == expected_sr_count
            ),
        }

    # -------------------------------------------------------------------------
    # Exact duplicate content
    # -------------------------------------------------------------------------

    duplicate_texts = find_duplicate_content(
        requirements
    )

    duplicate_text_report = [
        {
            "ids": ids,
            "text": text,
        }
        for text, ids in duplicate_texts.items()
    ]

    # -------------------------------------------------------------------------
    # Per-entry audit
    # -------------------------------------------------------------------------

    entry_audits = []

    for requirement in requirements:

        audit = audit_requirement(
            requirement=requirement,
            all_clean_ids=all_clean_ids,
            debug_candidates_by_id=debug_candidates_by_id,
            consolidated_debug=consolidated_debug,
        )

        entry_audits.append(audit)

    # -------------------------------------------------------------------------
    # Status counts
    # -------------------------------------------------------------------------

    status_counts = Counter(
        audit["status"]
        for audit in entry_audits
    )

    # -------------------------------------------------------------------------
    # Missing debug entries
    # -------------------------------------------------------------------------

    missing_from_debug_blocks = [
        audit["id"]
        for audit in entry_audits
        if audit["debug_candidate_audit"]
        ["candidate_occurrences"] == 0
    ]

    # -------------------------------------------------------------------------
    # Missing debug consolidation
    # -------------------------------------------------------------------------

    missing_from_debug_consolidation = [
        audit["id"]
        for audit in entry_audits
        if not audit["debug_consolidated_comparison"]
        ["found"]
    ]

    # -------------------------------------------------------------------------
    # Dataset structural result
    # -------------------------------------------------------------------------

    structural_pass = (
        len(requirements) == EXPECTED_TOTAL_ENTRIES
        and len(sr_entries) == EXPECTED_TOTAL_SRS
        and len(re_entries) == EXPECTED_TOTAL_RES
        and not duplicate_ids
        and not missing_srs
        and not unexpected_srs
    )

    return {
        "metadata": {
            "audit_generated_at": (
                datetime.now(timezone.utc)
                .isoformat()
            ),
            "audit_script": "iec_audit.py",
            "clean_dataset": str(CLEAN_JSON_PATH),
            "debug_dataset": str(DEBUG_JSON_PATH),
            "expected_total_entries": EXPECTED_TOTAL_ENTRIES,
            "expected_total_srs": EXPECTED_TOTAL_SRS,
            "expected_total_res": EXPECTED_TOTAL_RES,
        },

        "dataset_summary": {
            "total_entries": len(requirements),
            "sr_count": len(sr_entries),
            "re_count": len(re_entries),

            "expected_total_entries": EXPECTED_TOTAL_ENTRIES,
            "expected_total_srs": EXPECTED_TOTAL_SRS,
            "expected_total_res": EXPECTED_TOTAL_RES,

            "structural_pass": structural_pass,

            "status_counts": dict(status_counts),

            "duplicate_id_count": len(duplicate_ids),

            "duplicate_text_group_count": len(
                duplicate_text_report
            ),

            "missing_sr_count": len(missing_srs),

            "unexpected_sr_count": len(
                unexpected_srs
            ),

            "missing_from_debug_blocks_count": len(
                missing_from_debug_blocks
            ),

            "missing_from_debug_consolidation_count": len(
                missing_from_debug_consolidation
            ),
        },

        "sr_coverage": {
            "expected_ids": sorted(EXPECTED_SR_IDS),
            "actual_ids": sorted(actual_sr_ids),
            "missing_ids": missing_srs,
            "unexpected_ids": unexpected_srs,
        },

        "foundational_requirement_distribution":
            fr_distribution,

        "duplicate_ids": duplicate_ids,

        "duplicate_texts": duplicate_text_report,

        "debug_coverage": {
            "missing_from_debug_blocks":
                missing_from_debug_blocks,

            "missing_from_debug_consolidation":
                missing_from_debug_consolidation,
        },

        "entries": entry_audits,
    }


# =============================================================================
# REPORT GENERATION
# =============================================================================

def write_report(
    audit_data: dict[str, Any],
    path: Path,
) -> None:
    """
    Writes a human-readable audit report.
    """

    summary = audit_data["dataset_summary"]

    lines = []

    lines.append("=" * 78)
    lines.append("IEC 62443-3-3 DATASET AUDIT REPORT")
    lines.append("=" * 78)

    lines.append("")
    lines.append(
        f"Generated at: "
        f"{audit_data['metadata']['audit_generated_at']}"
    )

    lines.append(
        f"Clean dataset: "
        f"{audit_data['metadata']['clean_dataset']}"
    )

    lines.append(
        f"Debug dataset: "
        f"{audit_data['metadata']['debug_dataset']}"
    )

    lines.append("")

    # -------------------------------------------------------------------------
    # Summary
    # -------------------------------------------------------------------------

    lines.append("-" * 78)
    lines.append("DATASET SUMMARY")
    lines.append("-" * 78)

    lines.append(
        f"Total entries : {summary['total_entries']}"
    )

    lines.append(
        f"SRs           : {summary['sr_count']}"
    )

    lines.append(
        f"REs           : {summary['re_count']}"
    )

    lines.append(
        f"Structural pass: "
        f"{'YES' if summary['structural_pass'] else 'NO'}"
    )

    lines.append("")

    lines.append("Entry status:")

    for status in [
        "approved",
        "warning",
        "review",
        "fail",
    ]:
        count = summary["status_counts"].get(status, 0)

        lines.append(
            f"  {status:10s}: {count}"
        )

    lines.append("")

    # -------------------------------------------------------------------------
    # SR coverage
    # -------------------------------------------------------------------------

    coverage = audit_data["sr_coverage"]

    lines.append("-" * 78)
    lines.append("SR COVERAGE")
    lines.append("-" * 78)

    if not coverage["missing_ids"]:
        lines.append(
            "All expected 51 SR IDs are present."
        )
    else:
        lines.append(
            f"Missing SR IDs ({len(coverage['missing_ids'])}):"
        )

        for requirement_id in coverage["missing_ids"]:
            lines.append(f"  - {requirement_id}")

    if coverage["unexpected_ids"]:

        lines.append("")
        lines.append(
            f"Unexpected SR IDs "
            f"({len(coverage['unexpected_ids'])}):"
        )

        for requirement_id in coverage["unexpected_ids"]:
            lines.append(f"  - {requirement_id}")

    lines.append("")

    # -------------------------------------------------------------------------
    # FR distribution
    # -------------------------------------------------------------------------

    lines.append("-" * 78)
    lines.append("FOUNDATIONAL REQUIREMENT DISTRIBUTION")
    lines.append("-" * 78)

    distribution = (
        audit_data[
            "foundational_requirement_distribution"
        ]
    )

    for fr in range(1, 8):

        info = distribution[str(fr)]

        symbol = (
            "OK"
            if info["sr_count_matches_expected"]
            else "WARNING"
        )

        lines.append(
            f"FR {fr}: "
            f"{info['sr_count']} SRs "
            f"(expected {info['expected_sr_count']}), "
            f"{info['re_count']} REs "
            f"[{symbol}]"
        )

    lines.append("")

    # -------------------------------------------------------------------------
    # Duplicate IDs
    # -------------------------------------------------------------------------

    lines.append("-" * 78)
    lines.append("DUPLICATE IDS")
    lines.append("-" * 78)

    duplicate_ids = audit_data["duplicate_ids"]

    if not duplicate_ids:
        lines.append("No duplicate IDs detected.")
    else:
        for requirement_id, count in duplicate_ids.items():
            lines.append(
                f"{requirement_id}: {count} occurrences"
            )

    lines.append("")

    # -------------------------------------------------------------------------
    # Debug coverage
    # -------------------------------------------------------------------------

    lines.append("-" * 78)
    lines.append("DEBUG COVERAGE")
    lines.append("-" * 78)

    debug_coverage = audit_data["debug_coverage"]

    missing_blocks = (
        debug_coverage["missing_from_debug_blocks"]
    )

    missing_consolidation = (
        debug_coverage[
            "missing_from_debug_consolidation"
        ]
    )

    lines.append(
        f"Missing from debug blocks: "
        f"{len(missing_blocks)}"
    )

    for requirement_id in missing_blocks:
        lines.append(f"  - {requirement_id}")

    lines.append(
        f"Missing from debug consolidation: "
        f"{len(missing_consolidation)}"
    )

    for requirement_id in missing_consolidation:
        lines.append(f"  - {requirement_id}")

    lines.append("")

    # -------------------------------------------------------------------------
    # Duplicate text
    # -------------------------------------------------------------------------

    lines.append("-" * 78)
    lines.append("EXACT DUPLICATE TEXT GROUPS")
    lines.append("-" * 78)

    duplicate_texts = audit_data["duplicate_texts"]

    if not duplicate_texts:
        lines.append("No exact duplicate text groups detected.")

    else:

        for duplicate in duplicate_texts:

            lines.append(
                "IDs: "
                + ", ".join(duplicate["ids"])
            )

            lines.append(
                "Text: "
                + duplicate["text"]
            )

            lines.append("")

    lines.append("")

    # -------------------------------------------------------------------------
    # Entries requiring attention
    # -------------------------------------------------------------------------

    lines.append("=" * 78)
    lines.append("ENTRIES REQUIRING ATTENTION")
    lines.append("=" * 78)

    attention_entries = [
        entry
        for entry in audit_data["entries"]
        if entry["status"] != "approved"
    ]

    if not attention_entries:

        lines.append(
            "No entries require attention."
        )

    else:

        for entry in attention_entries:

            lines.append("")
            lines.append("-" * 78)

            lines.append(
                f"{entry['id']} | "
                f"{entry['type']} | "
                f"STATUS: {entry['status'].upper()}"
            )

            lines.append(
                f"Score: "
                f"{entry['score']}/{entry['max_score']}"
            )

            lines.append(
                f"Title: {entry['title']}"
            )

            lines.append(
                f"Words: {entry['word_count']}"
            )

            if entry["issues"]:

                lines.append("Issues:")

                for issue in entry["issues"]:
                    lines.append(f"  - {issue}")

            if entry["warnings"]:

                lines.append("Warnings:")

                for warning in entry["warnings"]:
                    lines.append(f"  - {warning}")

            debug_audit = (
                entry["debug_candidate_audit"]
            )

            lines.append(
                f"Debug occurrences: "
                f"{debug_audit['candidate_occurrences']}"
            )

            lines.append(
                f"Unique text variants: "
                f"{debug_audit['unique_text_variants']}"
            )

            lines.append(
                f"Minimum similarity to final: "
                f"{debug_audit['min_text_similarity_to_final']}"
            )

            if debug_audit["text_variants"]:

                lines.append("")
                lines.append(
                    "Debug text variants:"
                )

                for variant in (
                    debug_audit["text_variants"]
                ):

                    lines.append(
                        f"  Blocks: {variant['blocks']}"
                    )

                    lines.append(
                        f"  Text: {variant['text']}"
                    )

                    lines.append("")

    lines.append("")
    lines.append("=" * 78)
    lines.append("END OF AUDIT REPORT")
    lines.append("=" * 78)

    with path.open("w", encoding="utf-8") as file:
        file.write("\n".join(lines))


# =============================================================================
# CONSOLE SUMMARY
# =============================================================================

def print_summary(
    audit_data: dict[str, Any]
) -> None:

    summary = audit_data["dataset_summary"]

    print()
    print("=" * 70)
    print("IEC 62443-3-3 AUDIT SUMMARY")
    print("=" * 70)
    print()

    print(
        f"Total entries : "
        f"{summary['total_entries']}"
    )

    print(
        f"SRs           : "
        f"{summary['sr_count']}"
    )

    print(
        f"REs           : "
        f"{summary['re_count']}"
    )

    print()

    print("Entry status:")

    for status in [
        "approved",
        "warning",
        "review",
        "fail",
    ]:

        count = (
            summary["status_counts"]
            .get(status, 0)
        )

        print(
            f"  {status:10s}: {count}"
        )

    print()

    structural = (
        summary["structural_pass"]
    )

    if structural:

        print(
            "Structural validation: "
            "PASSED"
        )

    else:

        print(
            "Structural validation: "
            "PROBLEMS FOUND"
        )

    print()

    print(
        f"Audit JSON saved to:\n"
        f"   {AUDIT_JSON_PATH}"
    )

    print()

    print(
        f"Audit report saved to:\n"
        f"   {AUDIT_REPORT_PATH}"
    )

    print()
    print("=" * 70)


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:

    print()
    print(
        "🔍 Starting IEC 62443-3-3 dataset audit..."
    )
    print()

    print(
        f"📄 Loading clean dataset:\n"
        f"   {CLEAN_JSON_PATH}"
    )

    clean_data = load_json(
        CLEAN_JSON_PATH
    )

    print()

    print(
        f"📄 Loading debug dataset:\n"
        f"   {DEBUG_JSON_PATH}"
    )

    debug_data = load_json(
        DEBUG_JSON_PATH
    )

    print()

    print(
        "🧪 Running structural and semantic audits..."
    )

    audit_data = audit_dataset(
        clean_data=clean_data,
        debug_data=debug_data,
    )

    # Ensure output directory exists.
    BASE_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    # -------------------------------------------------------------------------
    # Save audit JSON
    # -------------------------------------------------------------------------

    with AUDIT_JSON_PATH.open(
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            audit_data,
            file,
            indent=2,
            ensure_ascii=False,
        )

    # -------------------------------------------------------------------------
    # Save human-readable report
    # -------------------------------------------------------------------------

    write_report(
        audit_data,
        AUDIT_REPORT_PATH,
    )

    # -------------------------------------------------------------------------
    # Console output
    # -------------------------------------------------------------------------

    print_summary(audit_data)

    summary = audit_data[
        "dataset_summary"
    ]

    if summary["structural_pass"]:

        print(
            "\n✅ Audit completed successfully."
        )

    else:

        print(
            "\n⚠️ Audit completed, "
            "but structural problems were found."
        )


if __name__ == "__main__":

    try:
        main()

    except KeyboardInterrupt:

        print(
            "\n\n⚠️ Audit interrupted by user."
        )

        sys.exit(130)

    except Exception as exc:

        print(
            "\n\n❌ AUDIT FAILED"
        )

        print(
            f"{type(exc).__name__}: {exc}"
        )

        sys.exit(1)